// Module2_FrontendDev/Ajay kumar/student-portal-react/src/components/Header.jsx
// src/components/Header.jsx
import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';

export default function Header({ siteName }) {
    // Read state directly from Redux store
    const enrolledCourses = useSelector(state => state.enrollment.enrolledCourses);

    return (
        <header style={{ backgroundColor: '#2c3e50', color: 'white', padding: '20px', display: 'flex', justifyContent: 'space-between' }}>
            <h2>{siteName}</h2>
            <nav style={{ display: 'flex', gap: '15px', alignItems: 'center' }}>
                <span style={{ fontWeight: 'bold', color: '#f1c40f' }}>
                    Enrolled: {enrolledCourses.length}
                </span>
                <Link to="/" style={{ color: 'white', textDecoration: 'none' }}>Home</Link>
                <Link to="/courses" style={{ color: 'white', textDecoration: 'none' }}>Courses</Link>
                <Link to="/profile" style={{ color: 'white', textDecoration: 'none' }}>Profile</Link>
            </nav>
        </header>
    );
}

// Module2_FrontendDev/Ajay kumar/student-portal-vue/src/components/Header.vue
<script setup>
import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()
</script>

<template>
  <header style="background-color: #2c3e50; color: white; padding: 20px; display: flex; justify-content: space-between;">
    <h2 style="margin: 0;">Student Portal (Vue)</h2>
    <nav style="display: flex; gap: 15px; align-items: center;">
      <span style="color: #f1c40f; font-weight: bold;">Enrolled: {{ store.enrolledCourses.length }}</span>
      <RouterLink to="/" style="color: white; text-decoration: none;">Home</RouterLink>
      <RouterLink to="/courses" style="color: white; text-decoration: none;">Courses</RouterLink>
      <RouterLink to="/profile" style="color: white; text-decoration: none;">Profile</RouterLink>
    </nav>
  </header>
</template>
